service: esa2slack
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
package:
 exclude:
   - ./**
 include:
   - ./bin/**

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 10

functions:
  hello:
    handler: bin/main
    events:
      - http:
          path: /
          method: post
    memorySize: 128
    environment:
      SLACK_WEB_HOOK_URL: ${env:SLACK_WEBHOOK_URL}
      ESA_TARGET_PATH: ${env:ESA_TARGET_PATH}
